version: '3.9'

services:
  api:
    build: .
    container_name: customer_insights_api
    ports:
      - "8000:8000"
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  web:
    build: .
    container_name: customer_insights_web
    ports:
      - "8501:8501"
    command: streamlit run src/webapp/app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
